;https://github.com/tindy2013/subconverter/blob/master/README-cn.md

[custom]

clash_rule_base=https://raw.githubusercontent.com/whaoa/sub-converter-config/main/base/clash.yaml

enable_rule_generator=true
overwrite_original_rules=true

custom_proxy_group=🎭 Proxy`select`[]🔰 Select`[]🇺🇸 UnitedStates`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]DIRECT
custom_proxy_group=🎯 Direct`select`[]DIRECT`[]🎭 Proxy
custom_proxy_group=🚦 Unmatch`select`[]🎯 Direct`[]🎭 Proxy
custom_proxy_group=🔰 Select`select`.*
custom_proxy_group=💬 Ai`select`[]🎭 Proxy`[]🔰 Select`[]🇺🇸 UnitedStates`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🎯 Direct
custom_proxy_group=📺 Bilibili`select`[]🎯 Direct`[]🔰 Select`[]🇭🇰 HongKong`[]🇨🇳 Taiwan`[]🎭 Proxy
custom_proxy_group=Ⓜ️ Microsoft`select`[]🎯 Direct`[]🎭 Proxy`[]🔰 Select`[]🇺🇸 UnitedStates`[]🇸🇬 Singapore`[]🇯🇵 Japan`[]🇭🇰 HongKong`[]🇨🇳 Taiwan
custom_proxy_group=🍃 Ban`select`[]REJECT`[]🎯 Direct
custom_proxy_group=🇺🇸 UnitedStates`url-test`(US|us|UnitedStates|United States|美国)`http://www.gstatic.com/generate_204`300,,150
custom_proxy_group=🇸🇬 Singapore`url-test`(SG|sg|Singapore|singapore|新加坡)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇯🇵 Japan`url-test`(JP|jp|Japan|japan|日本)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇭🇰 HongKong`url-test`(HK|hk|HongKong|hongkong|Hong Kong|香港)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🇨🇳 Taiwan`url-test`(TW|tw|Taiwan|taiwan|台湾)`http://www.gstatic.com/generate_204`300,,50

ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=🍃 Ban,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 Ban,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
;ruleset=🍃 Ban,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
;ruleset=🍃 Ban,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
;ruleset=🍃 Ban,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=📺 Bilibili,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
ruleset=📺 Bilibili,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/whaoa/sub-converter-config/main/rulesets/ncat.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/whaoa/sub-converter-config/main/rulesets/mtyy.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/whaoa/sub-converter-config/main/rulesets/okzyw.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/whaoa/sub-converter-config/main/rulesets/xmfyy.list
ruleset=🎯 Direct,https://raw.githubusercontent.com/whaoa/sub-converter-config/main/rulesets/nmsp.list
ruleset=💬 Ai,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🎭 Proxy,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🎭 Proxy,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🎭 Proxy,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=🎯 Direct,[]GEOIP,CN
ruleset=🚦 Unmatch,[]FINAL
